title: Sowgoto Raha Sunny
logo: assets/images/Sunny pic.jpeg
description: "I am pursuing graduate studies and passionate about technology, design, and creative writing."
theme: jekyll-theme-architect
#show_downloads: true
