title: Sowgoto Raha Sunny
logo: assets/images/Sunny pic.jpeg
description: Graduate Teacher Assistant, University Of North Texas
<p>{{ site.description }}</p>
<a href="{{ https://informationscience.unt.edu/index.html }}" target="_blank">Information Science Department</a>
# show_downloads: true
theme: jekyll-theme-minimal

