title: Sowgoto Raha Sunny
logo: /assets/images/Sunny_pic.jpeg
description: "I am pursuing graduate studies and passionate about technology, design, and creative writing."
theme: jekyll-theme-minimal
show_downloads: true



