title: Sowgoto Raha Sunny
logo: assets/images/Sunny pic.jpeg
description: Graduate Teacher Assistant, University Of North Texas
department_link: "https://informationscience.unt.edu/index.html"
theme: jekyll-theme-minimal


