title: Sowgoto Raha Sunny
logo: assets/images/Sunny pic.jpeg
description: I am pursuing graduate studies.I am pursuing graduate studies. Qualified Linux Administrator adept at installing and maintaining Linux 
servers, improving server security, and health status, and providing technical assistance to clients with 
more than five years of cumulative professional experience in Database technology, Database 
Development, PL/SQL database design, and data visualizations. Also, my objective is to contribute to a 
secure digital environment, protecting valuable data and resources from potential cyber threats.
show_downloads: true
theme: jekyll-theme-minimal
